### ISSUE TITLE
IP Address Can't Be Found

### ISSUE THREAD

**Issue by R4356th** [colbygk/colbygk.github.io#1]
Whenever I try to visit this site, I get a message from my browser saying that it's IP Address couldn't be found. @colbygk , did you delete or remove it?

**Comment by colbygk** [comment]
Oh, I was experimenting with github.io a few years before they started offering the ability to have proper SSL/TLS SNI certs... might go back to using it...

**Comment by R4356th** [comment]
> Oh, I was experimenting with github.io a few years before they started offering the ability to have proper SSL/TLS SNI certs... might go back to using it...

Oh, okay.

**Comment by R4356th** [comment]
Closing issue.
